const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
const LOAD_COURSES_FAILURE = 'LOAD_COURSES_FAILURE';
const CREATE_COURSE_SUCCESS = 'CREATE_COURSE_SUCCESS';
const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
const SAVE_COURSE_FAILURE = 'SAVE_COURSE_FAILURE';

export default {
    LOAD_COURSES_SUCCESS,
    LOAD_COURSES_FAILURE,
    CREATE_COURSE_SUCCESS,
    UPDATE_COURSE_SUCCESS,
    SAVE_COURSE_FAILURE
};
